/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';
import DireccionDTO from './DireccionDTO.js';

/**
 * The EmpleadoDTO model module.
 * @module model/EmpleadoDTO
 * @version 1.0
 */
export default class EmpleadoDTO {
  /**
   * Constructs a new <code>EmpleadoDTO</code>.
   * @alias module:model/EmpleadoDTO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EmpleadoDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EmpleadoDTO} obj Optional instance to populate.
   * @return {module:model/EmpleadoDTO} The populated <code>EmpleadoDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EmpleadoDTO();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('nombre'))
        obj.nombre = ApiClient.convertToType(data['nombre'], 'String');
      if (data.hasOwnProperty('apellido1'))
        obj.apellido1 = ApiClient.convertToType(data['apellido1'], 'String');
      if (data.hasOwnProperty('apellido2'))
        obj.apellido2 = ApiClient.convertToType(data['apellido2'], 'String');
      if (data.hasOwnProperty('dniNie'))
        obj.dniNie = ApiClient.convertToType(data['dniNie'], 'String');
      if (data.hasOwnProperty('telefono'))
        obj.telefono = ApiClient.convertToType(data['telefono'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('tipo_empleado_id'))
        obj.tipoEmpleadoId = ApiClient.convertToType(data['tipo_empleado_id'], 'Number');
      if (data.hasOwnProperty('tipo_empleado_nombre'))
        obj.tipoEmpleadoNombre = ApiClient.convertToType(data['tipo_empleado_nombre'], 'String');
      if (data.hasOwnProperty('rol_id'))
        obj.rolId = ApiClient.convertToType(data['rol_id'], 'Number');
      if (data.hasOwnProperty('direccion'))
        obj.direccion = DireccionDTO.constructFromObject(data['direccion']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
EmpleadoDTO.prototype.id = undefined;

/**
 * @member {String} nombre
 */
EmpleadoDTO.prototype.nombre = undefined;

/**
 * @member {String} apellido1
 */
EmpleadoDTO.prototype.apellido1 = undefined;

/**
 * @member {String} apellido2
 */
EmpleadoDTO.prototype.apellido2 = undefined;

/**
 * @member {String} dniNie
 */
EmpleadoDTO.prototype.dniNie = undefined;

/**
 * @member {String} telefono
 */
EmpleadoDTO.prototype.telefono = undefined;

/**
 * @member {String} email
 */
EmpleadoDTO.prototype.email = undefined;

/**
 * @member {String} password
 */
EmpleadoDTO.prototype.password = undefined;

/**
 * @member {Number} tipoEmpleadoId
 */
EmpleadoDTO.prototype.tipoEmpleadoId = undefined;

/**
 * @member {String} tipoEmpleadoNombre
 */
EmpleadoDTO.prototype.tipoEmpleadoNombre = undefined;

/**
 * @member {Number} rolId
 */
EmpleadoDTO.prototype.rolId = undefined;

/**
 * @member {module:model/DireccionDTO} direccion
 */
EmpleadoDTO.prototype.direccion = undefined;

