/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The Localidad model module.
 * @module model/Localidad
 * @version 1.0
 */
export default class Localidad {
  /**
   * Constructs a new <code>Localidad</code>.
   * @alias module:model/Localidad
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Localidad</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Localidad} obj Optional instance to populate.
   * @return {module:model/Localidad} The populated <code>Localidad</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Localidad();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('nombre'))
        obj.nombre = ApiClient.convertToType(data['nombre'], 'String');
      if (data.hasOwnProperty('codigoPostal'))
        obj.codigoPostal = ApiClient.convertToType(data['codigoPostal'], 'Number');
      if (data.hasOwnProperty('provinciaId'))
        obj.provinciaId = ApiClient.convertToType(data['provinciaId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Localidad.prototype.id = undefined;

/**
 * @member {String} nombre
 */
Localidad.prototype.nombre = undefined;

/**
 * @member {Number} codigoPostal
 */
Localidad.prototype.codigoPostal = undefined;

/**
 * @member {Number} provinciaId
 */
Localidad.prototype.provinciaId = undefined;

