/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The ProductoCreateBody model module.
 * @module model/ProductoCreateBody
 * @version 1.0
 */
export default class ProductoCreateBody {
  /**
   * Constructs a new <code>ProductoCreateBody</code>.
   * @alias module:model/ProductoCreateBody
   * @class
   * @param nombre {String} Nombre del producto
   * @param precio {Number} Precio del producto
   * @param stockDisponible {Number} Stock disponible del producto
   * @param idCategoria {Number} ID de la categoría
   * @param idMarca {Number} ID de la marca
   * @param idUnidadMedida {Number} ID de la unidad de medida
   */
  constructor(nombre, precio, stockDisponible, idCategoria, idMarca, idUnidadMedida) {
    this.nombre = nombre;
    this.precio = precio;
    this.stockDisponible = stockDisponible;
    this.idCategoria = idCategoria;
    this.idMarca = idMarca;
    this.idUnidadMedida = idUnidadMedida;
  }

  /**
   * Constructs a <code>ProductoCreateBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductoCreateBody} obj Optional instance to populate.
   * @return {module:model/ProductoCreateBody} The populated <code>ProductoCreateBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductoCreateBody();
      if (data.hasOwnProperty('nombre'))
        obj.nombre = ApiClient.convertToType(data['nombre'], 'String');
      if (data.hasOwnProperty('descripcion'))
        obj.descripcion = ApiClient.convertToType(data['descripcion'], 'String');
      if (data.hasOwnProperty('precio'))
        obj.precio = ApiClient.convertToType(data['precio'], 'Number');
      if (data.hasOwnProperty('stockDisponible'))
        obj.stockDisponible = ApiClient.convertToType(data['stockDisponible'], 'Number');
      if (data.hasOwnProperty('idCategoria'))
        obj.idCategoria = ApiClient.convertToType(data['idCategoria'], 'Number');
      if (data.hasOwnProperty('idMarca'))
        obj.idMarca = ApiClient.convertToType(data['idMarca'], 'Number');
      if (data.hasOwnProperty('idUnidadMedida'))
        obj.idUnidadMedida = ApiClient.convertToType(data['idUnidadMedida'], 'Number');
    }
    return obj;
  }
}

/**
 * Nombre del producto
 * @member {String} nombre
 */
ProductoCreateBody.prototype.nombre = undefined;

/**
 * Descripción del producto
 * @member {String} descripcion
 */
ProductoCreateBody.prototype.descripcion = undefined;

/**
 * Precio del producto
 * @member {Number} precio
 */
ProductoCreateBody.prototype.precio = undefined;

/**
 * Stock disponible del producto
 * @member {Number} stockDisponible
 */
ProductoCreateBody.prototype.stockDisponible = undefined;

/**
 * ID de la categoría
 * @member {Number} idCategoria
 */
ProductoCreateBody.prototype.idCategoria = undefined;

/**
 * ID de la marca
 * @member {Number} idMarca
 */
ProductoCreateBody.prototype.idMarca = undefined;

/**
 * ID de la unidad de medida
 * @member {Number} idUnidadMedida
 */
ProductoCreateBody.prototype.idUnidadMedida = undefined;

