/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient.js';
import ClienteDTO from './model/ClienteDTO.js';
import ClienteRegistrarBody from './model/ClienteRegistrarBody.js';
import DireccionDTO from './model/DireccionDTO.js';
import EmpleadoDTO from './model/EmpleadoDTO.js';
import FormDataContentDisposition from './model/FormDataContentDisposition.js';
import LineaPedido from './model/LineaPedido.js';
import Localidad from './model/Localidad.js';
import Pais from './model/Pais.js';
import Pedido from './model/Pedido.js';
import ProductoDTO from './model/ProductoDTO.js';
import ProductoProductoIdBody from './model/ProductoProductoIdBody.js';
import Provincia from './model/Provincia.js';
import Results from './model/Results.js';
import DefaultApi from './api/DefaultApi.js';

/**
* API_para_gestionar_tienda_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CiberLojaApi = require('index'); // See note below*.
* var xxxSvc = new CiberLojaApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CiberLojaApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CiberLojaApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CiberLojaApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ClienteDTO model constructor.
     * @property {module:model/ClienteDTO}
     */
    ClienteDTO,

    /**
     * The ClienteRegistrarBody model constructor.
     * @property {module:model/ClienteRegistrarBody}
     */
    ClienteRegistrarBody,

    /**
     * The DireccionDTO model constructor.
     * @property {module:model/DireccionDTO}
     */
    DireccionDTO,

    /**
     * The EmpleadoDTO model constructor.
     * @property {module:model/EmpleadoDTO}
     */
    EmpleadoDTO,

    /**
     * The FormDataContentDisposition model constructor.
     * @property {module:model/FormDataContentDisposition}
     */
    FormDataContentDisposition,

    /**
     * The LineaPedido model constructor.
     * @property {module:model/LineaPedido}
     */
    LineaPedido,

    /**
     * The Localidad model constructor.
     * @property {module:model/Localidad}
     */
    Localidad,

    /**
     * The Pais model constructor.
     * @property {module:model/Pais}
     */
    Pais,

    /**
     * The Pedido model constructor.
     * @property {module:model/Pedido}
     */
    Pedido,

    /**
     * The ProductoDTO model constructor.
     * @property {module:model/ProductoDTO}
     */
    ProductoDTO,

    /**
     * The ProductoProductoIdBody model constructor.
     * @property {module:model/ProductoProductoIdBody}
     */
    ProductoProductoIdBody,

    /**
     * The Provincia model constructor.
     * @property {module:model/Provincia}
     */
    Provincia,

    /**
     * The Results model constructor.
     * @property {module:model/Results}
     */
    Results,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
