/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The LineaPedido model module.
 * @module model/LineaPedido
 * @version 1.0
 */
export default class LineaPedido {
  /**
   * Constructs a new <code>LineaPedido</code>.
   * @alias module:model/LineaPedido
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LineaPedido</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LineaPedido} obj Optional instance to populate.
   * @return {module:model/LineaPedido} The populated <code>LineaPedido</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LineaPedido();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('precio'))
        obj.precio = ApiClient.convertToType(data['precio'], 'Number');
      if (data.hasOwnProperty('productoId'))
        obj.productoId = ApiClient.convertToType(data['productoId'], 'String');
      if (data.hasOwnProperty('nombreProducto'))
        obj.nombreProducto = ApiClient.convertToType(data['nombreProducto'], 'String');
      if (data.hasOwnProperty('pedidoId'))
        obj.pedidoId = ApiClient.convertToType(data['pedidoId'], 'Number');
      if (data.hasOwnProperty('unidades'))
        obj.unidades = ApiClient.convertToType(data['unidades'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
LineaPedido.prototype.id = undefined;

/**
 * @member {Number} precio
 */
LineaPedido.prototype.precio = undefined;

/**
 * @member {String} productoId
 */
LineaPedido.prototype.productoId = undefined;

/**
 * @member {String} nombreProducto
 */
LineaPedido.prototype.nombreProducto = undefined;

/**
 * @member {Number} pedidoId
 */
LineaPedido.prototype.pedidoId = undefined;

/**
 * @member {Number} unidades
 */
LineaPedido.prototype.unidades = undefined;

