/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The Pais model module.
 * @module model/Pais
 * @version 1.0
 */
export default class Pais {
  /**
   * Constructs a new <code>Pais</code>.
   * @alias module:model/Pais
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Pais</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Pais} obj Optional instance to populate.
   * @return {module:model/Pais} The populated <code>Pais</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Pais();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('nombre'))
        obj.nombre = ApiClient.convertToType(data['nombre'], 'String');
      if (data.hasOwnProperty('iso1'))
        obj.iso1 = ApiClient.convertToType(data['iso1'], 'String');
      if (data.hasOwnProperty('iso2'))
        obj.iso2 = ApiClient.convertToType(data['iso2'], 'String');
      if (data.hasOwnProperty('phoneCodigo'))
        obj.phoneCodigo = ApiClient.convertToType(data['phoneCodigo'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Pais.prototype.id = undefined;

/**
 * @member {String} nombre
 */
Pais.prototype.nombre = undefined;

/**
 * @member {String} iso1
 */
Pais.prototype.iso1 = undefined;

/**
 * @member {String} iso2
 */
Pais.prototype.iso2 = undefined;

/**
 * @member {String} phoneCodigo
 */
Pais.prototype.phoneCodigo = undefined;

