/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The ProductoDTO model module.
 * @module model/ProductoDTO
 * @version 1.0
 */
export default class ProductoDTO {
  /**
   * Constructs a new <code>ProductoDTO</code>.
   * @alias module:model/ProductoDTO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProductoDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductoDTO} obj Optional instance to populate.
   * @return {module:model/ProductoDTO} The populated <code>ProductoDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductoDTO();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('nombre'))
        obj.nombre = ApiClient.convertToType(data['nombre'], 'String');
      if (data.hasOwnProperty('descripcion'))
        obj.descripcion = ApiClient.convertToType(data['descripcion'], 'String');
      if (data.hasOwnProperty('precio'))
        obj.precio = ApiClient.convertToType(data['precio'], 'Number');
      if (data.hasOwnProperty('stockDisponible'))
        obj.stockDisponible = ApiClient.convertToType(data['stockDisponible'], 'Number');
      if (data.hasOwnProperty('idCategoria'))
        obj.idCategoria = ApiClient.convertToType(data['idCategoria'], 'Number');
      if (data.hasOwnProperty('nombreCategoria'))
        obj.nombreCategoria = ApiClient.convertToType(data['nombreCategoria'], 'String');
      if (data.hasOwnProperty('idMarca'))
        obj.idMarca = ApiClient.convertToType(data['idMarca'], 'Number');
      if (data.hasOwnProperty('nombreMarca'))
        obj.nombreMarca = ApiClient.convertToType(data['nombreMarca'], 'String');
      if (data.hasOwnProperty('idUnidadMedida'))
        obj.idUnidadMedida = ApiClient.convertToType(data['idUnidadMedida'], 'Number');
      if (data.hasOwnProperty('nombreUnidadMedida'))
        obj.nombreUnidadMedida = ApiClient.convertToType(data['nombreUnidadMedida'], 'String');
      if (data.hasOwnProperty('imagenUrl'))
        obj.imagenUrl = ApiClient.convertToType(data['imagenUrl'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
ProductoDTO.prototype.id = undefined;

/**
 * @member {String} nombre
 */
ProductoDTO.prototype.nombre = undefined;

/**
 * @member {String} descripcion
 */
ProductoDTO.prototype.descripcion = undefined;

/**
 * @member {Number} precio
 */
ProductoDTO.prototype.precio = undefined;

/**
 * @member {Number} stockDisponible
 */
ProductoDTO.prototype.stockDisponible = undefined;

/**
 * @member {Number} idCategoria
 */
ProductoDTO.prototype.idCategoria = undefined;

/**
 * @member {String} nombreCategoria
 */
ProductoDTO.prototype.nombreCategoria = undefined;

/**
 * @member {Number} idMarca
 */
ProductoDTO.prototype.idMarca = undefined;

/**
 * @member {String} nombreMarca
 */
ProductoDTO.prototype.nombreMarca = undefined;

/**
 * @member {Number} idUnidadMedida
 */
ProductoDTO.prototype.idUnidadMedida = undefined;

/**
 * @member {String} nombreUnidadMedida
 */
ProductoDTO.prototype.nombreUnidadMedida = undefined;

/**
 * @member {String} imagenUrl
 */
ProductoDTO.prototype.imagenUrl = undefined;

