/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';
import FormDataContentDisposition from './FormDataContentDisposition.js';

/**
 * The ProductoProductoIdBody model module.
 * @module model/ProductoProductoIdBody
 * @version 1.0
 */
export default class ProductoProductoIdBody {
  /**
   * Constructs a new <code>ProductoProductoIdBody</code>.
   * @alias module:model/ProductoProductoIdBody
   * @class
   * @param file {module:model/FormDataContentDisposition} 
   */
  constructor(file) {
    this.file = file;
  }

  /**
   * Constructs a <code>ProductoProductoIdBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductoProductoIdBody} obj Optional instance to populate.
   * @return {module:model/ProductoProductoIdBody} The populated <code>ProductoProductoIdBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductoProductoIdBody();
      if (data.hasOwnProperty('file'))
        obj.file = FormDataContentDisposition.constructFromObject(data['file']);
    }
    return obj;
  }
}

/**
 * @member {module:model/FormDataContentDisposition} file
 */
ProductoProductoIdBody.prototype.file = undefined;

