/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The ProductoDTO model module.
 * @module model/ProductoDTO
 * @version 1.0
 */
export default class ProductoDTO {
  /**
   * Constructs a new <code>ProductoDTO</code>.
   * @alias module:model/ProductoDTO
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ProductoDTO</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductoDTO} obj Optional instance to populate.
   * @return {module:model/ProductoDTO} The populated <code>ProductoDTO</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductoDTO();
      if (data.hasOwnProperty('familia'))
        obj.familia = ApiClient.convertToType(data['familia'], 'String');
      if (data.hasOwnProperty('familiaNombre'))
        obj.familiaNombre = ApiClient.convertToType(data['familiaNombre'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('nombre'))
        obj.nombre = ApiClient.convertToType(data['nombre'], 'String');
      if (data.hasOwnProperty('precio'))
        obj.precio = ApiClient.convertToType(data['precio'], 'Number');
      if (data.hasOwnProperty('stockDisponible'))
        obj.stockDisponible = ApiClient.convertToType(data['stockDisponible'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} familia
 */
ProductoDTO.prototype.familia = undefined;

/**
 * @member {String} familiaNombre
 */
ProductoDTO.prototype.familiaNombre = undefined;

/**
 * @member {String} id
 */
ProductoDTO.prototype.id = undefined;

/**
 * @member {String} nombre
 */
ProductoDTO.prototype.nombre = undefined;

/**
 * @member {Number} precio
 */
ProductoDTO.prototype.precio = undefined;

/**
 * @member {Number} stockDisponible
 */
ProductoDTO.prototype.stockDisponible = undefined;

