/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The ClienteRegistrarBody model module.
 * @module model/ClienteRegistrarBody
 * @version 1.0
 */
export default class ClienteRegistrarBody {
  /**
   * Constructs a new <code>ClienteRegistrarBody</code>.
   * @alias module:model/ClienteRegistrarBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ClienteRegistrarBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClienteRegistrarBody} obj Optional instance to populate.
   * @return {module:model/ClienteRegistrarBody} The populated <code>ClienteRegistrarBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ClienteRegistrarBody();
      if (data.hasOwnProperty('nombre'))
        obj.nombre = ApiClient.convertToType(data['nombre'], 'String');
      if (data.hasOwnProperty('nickname'))
        obj.nickname = ApiClient.convertToType(data['nickname'], 'String');
      if (data.hasOwnProperty('primerApellido'))
        obj.primerApellido = ApiClient.convertToType(data['primerApellido'], 'String');
      if (data.hasOwnProperty('segundoApellido'))
        obj.segundoApellido = ApiClient.convertToType(data['segundoApellido'], 'String');
      if (data.hasOwnProperty('dni'))
        obj.dni = ApiClient.convertToType(data['dni'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('telefono'))
        obj.telefono = ApiClient.convertToType(data['telefono'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} nombre
 */
ClienteRegistrarBody.prototype.nombre = undefined;

/**
 * @member {String} nickname
 */
ClienteRegistrarBody.prototype.nickname = undefined;

/**
 * @member {String} primerApellido
 */
ClienteRegistrarBody.prototype.primerApellido = undefined;

/**
 * @member {String} segundoApellido
 */
ClienteRegistrarBody.prototype.segundoApellido = undefined;

/**
 * @member {String} dni
 */
ClienteRegistrarBody.prototype.dni = undefined;

/**
 * @member {String} email
 */
ClienteRegistrarBody.prototype.email = undefined;

/**
 * @member {String} telefono
 */
ClienteRegistrarBody.prototype.telefono = undefined;

/**
 * @member {String} password
 */
ClienteRegistrarBody.prototype.password = undefined;

