/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';
import LineaPedido from './LineaPedido.js';

/**
 * The Pedido model module.
 * @module model/Pedido
 * @version 1.0
 */
export default class Pedido {
  /**
   * Constructs a new <code>Pedido</code>.
   * @alias module:model/Pedido
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Pedido</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Pedido} obj Optional instance to populate.
   * @return {module:model/Pedido} The populated <code>Pedido</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Pedido();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('fechaRealizacion'))
        obj.fechaRealizacion = ApiClient.convertToType(data['fechaRealizacion'], 'Date');
      if (data.hasOwnProperty('precio'))
        obj.precio = ApiClient.convertToType(data['precio'], 'Number');
      if (data.hasOwnProperty('clienteId'))
        obj.clienteId = ApiClient.convertToType(data['clienteId'], 'Number');
      if (data.hasOwnProperty('nickname'))
        obj.nickname = ApiClient.convertToType(data['nickname'], 'String');
      if (data.hasOwnProperty('tipoEstadoPedidoId'))
        obj.tipoEstadoPedidoId = ApiClient.convertToType(data['tipoEstadoPedidoId'], 'Number');
      if (data.hasOwnProperty('tipoEstadoPedidoNombre'))
        obj.tipoEstadoPedidoNombre = ApiClient.convertToType(data['tipoEstadoPedidoNombre'], 'String');
      if (data.hasOwnProperty('lineas'))
        obj.lineas = ApiClient.convertToType(data['lineas'], [LineaPedido]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Pedido.prototype.id = undefined;

/**
 * @member {Date} fechaRealizacion
 */
Pedido.prototype.fechaRealizacion = undefined;

/**
 * @member {Number} precio
 */
Pedido.prototype.precio = undefined;

/**
 * @member {Number} clienteId
 */
Pedido.prototype.clienteId = undefined;

/**
 * @member {String} nickname
 */
Pedido.prototype.nickname = undefined;

/**
 * @member {Number} tipoEstadoPedidoId
 */
Pedido.prototype.tipoEstadoPedidoId = undefined;

/**
 * @member {String} tipoEstadoPedidoNombre
 */
Pedido.prototype.tipoEstadoPedidoNombre = undefined;

/**
 * @member {Array.<module:model/LineaPedido>} lineas
 */
Pedido.prototype.lineas = undefined;

