/*
 * CiberLoja API
 * API para gestionar tienda 
 *
 * OpenAPI spec version: 1.0
 * Contact: soporte@reflevision.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient.js';

/**
 * The Provincia model module.
 * @module model/Provincia
 * @version 1.0
 */
export default class Provincia {
  /**
   * Constructs a new <code>Provincia</code>.
   * @alias module:model/Provincia
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Provincia</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Provincia} obj Optional instance to populate.
   * @return {module:model/Provincia} The populated <code>Provincia</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Provincia();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('nombre'))
        obj.nombre = ApiClient.convertToType(data['nombre'], 'String');
      if (data.hasOwnProperty('paisId'))
        obj.paisId = ApiClient.convertToType(data['paisId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Provincia.prototype.id = undefined;

/**
 * @member {String} nombre
 */
Provincia.prototype.nombre = undefined;

/**
 * @member {Number} paisId
 */
Provincia.prototype.paisId = undefined;

