
package com.luis.ciberloja.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WebsiteSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebsiteSoap {


    /**
     * Serviço que devolve os artigos para site
     * 
     * @param password
     * @param utilizador
     * @param empresa
     * @return
     *     returns com.luis.ciberloja.soap.GetArtigosCiberlojaSiteResponse.GetArtigosCiberlojaSiteResult
     */
    @WebMethod(operationName = "GetArtigosCiberlojaSite", action = "http://tempuri.org/GetArtigosCiberlojaSite")
    @WebResult(name = "GetArtigosCiberlojaSiteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetArtigosCiberlojaSite", targetNamespace = "http://tempuri.org/", className = "com.luis.ciberloja.soap.GetArtigosCiberlojaSite")
    @ResponseWrapper(localName = "GetArtigosCiberlojaSiteResponse", targetNamespace = "http://tempuri.org/", className = "com.luis.ciberloja.soap.GetArtigosCiberlojaSiteResponse")
    public com.luis.ciberloja.soap.GetArtigosCiberlojaSiteResponse.GetArtigosCiberlojaSiteResult getArtigosCiberlojaSite(
        @WebParam(name = "empresa", targetNamespace = "http://tempuri.org/")
        String empresa,
        @WebParam(name = "utilizador", targetNamespace = "http://tempuri.org/")
        String utilizador,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

}
